version: '3'
services:
  minio:
    image: minio/minio
    volumes:
      - './data:/data'
    ports:
      - '9000:9000'
    environment:
      MINIO_ACCESS_KEY: F6WUUG27HBUFSIXVZL59
      MINIO_SECRET_KEY: BPlIUU6SX0ZxiCMo3tIpCMAUdnmkN9Eo9K42NsRR
    command: server /data
  download-service:
    image: download-service
    build: .
    env_file:
      - ../kdrive.env
    ports:
      - 8080:8080
    depends_on:
      - minio
      